### ISSUE TITLE
最新版のDevel::KYTProfだとエラーになる

### ISSUE THREAD

**Issue by kazuph** [dann/p5-plack-middleware-profiler-kytprof#2]
日本語で失礼します。

https://github.com/dann/p5-plack-middleware-profiler-kytprof/blob/master/lib/Plack/Middleware/Profiler/KYTProf/Profile/TemplateEngine.pm

この部分でDevel::KYTProf->add_profを使ってる部分で

``` perl
    Devel::KYTProf->add_prof(
        "Text::Xslate",
        "render",
        sub {
            my ( $orig, $self, $file, $args ) = @_;
            return sprintf '%s %s', "render", $file;
        }
    );
```

こんな感じにcallback部分で文字列をスカラーで返してると思いますが、最新版のDevel::KYTProfだとこれによって以下のようなエラーが起きます。

```
Can't use string ("render index.tx") as an ARRAY ref while "strict refs" in use at /Users/{MyUserName}/.plenv/versions/5.16.2/lib/perl5/site_perl/5.16.2/Devel/KYTProf.pm line 252.
```

確認したところDevel::KYTProfのVersion 0.02までだとうまくいって、今年の2月19以降に修正された0.03以降からは上記のようなエラーが出ることが確認できました。

ちなみにPlack::Middleware::Profiler::KYTProf を使わずに単純にDevel::KYTProfを使った場合でも同様のエラーが出ることを確認しました。

``` perl
use Devel::KYTProf;
Devel::KYTProf->add_prof(
    "Text::Xslate",
    "render",
    sub {
        my ($orig, $self, $file, $args) = @_;
        return sprintf '%s %s', "render", $file;
    }
);
```

最新版のDevel::KYTProfの場合はreturn部分をArray refにすることで正常に動作することが確認できました。

``` perl
        return [sprintf '%s %s', "render", $file];
```

出力

```
21.312 ms  [Text::Xslate]  render index.tx  | MyApp::Web:37
```

本家のDevel::KYTProfの動作が変わってしまってることが原因なのでこちらにpull reqしていいか迷ったのでIssueの方に書かせて頂きました。

対応はお任せします。

**Comment by dann** [comment]
ありがとうございます！

Devel::KYTProfもバージョン番号的にα版という位置づけでしょうし、
public APIが変わってしまうのも致し方ないところですかね。

Devel::KYTProfの最新のAPIにあわせて、shipしておきました。
API非互換が頻繁にあるようであれば、defaultのprofileは削除しようかなと。

**Comment by kazuph** [comment]
対応ありがとうございます！
これからも使わせて頂きます。
